#pragma once

#include "core/types.hpp"
#include <opencv2/core.hpp>
#include <string>

namespace baddy {

// ── Camera configuration ──────────────────────────────────────────
struct CameraConfig {
    int    fps                      = 100;
    int    width                    = 1920;
    int    height                   = 1200;
    double exposure_us              = 5000;
    double gain_db                  = 0;
    int    white_balance_temperature = 4500;
    bool   white_balance_auto       = false;
    std::string pixel_format        = "BayerRG8";
    std::string primary_serial;
    std::string secondary_serial;
};

// ── Detection configuration ───────────────────────────────────────
struct DetectionConfig {
    int hsv_low[3]        = {140, 80, 80};
    int hsv_high[3]       = {179, 255, 255};
    int min_contour_area  = 5;
    int morph_kernel_size = 7;
};

// ── EKF / prediction configuration ───────────────────────────────
struct EkfConfig {
    double alpha    = 0.215;
    double gravity  = 9.81;

    double sigma_p      = 0.05;
    double sigma_v      = 2.0;
    double sigma_cam_x  = 0.02;
    double sigma_cam_y  = 0.02;
    double sigma_cam_z  = 0.05;

    int    max_coast_frames   = 30;
    double target_intercept_y = 0.0;
    double max_predict_time   = 3.0;

    double initial_p_position = 1.0;
    double initial_p_velocity = 100.0;

    // Coordinate remap for the paper dataset.
    std::string x_source = "X";
    std::string y_source = "Z";
    std::string z_source = "Y";
    double x_offset = 3.05;
    double y_offset = 0.0;
    double z_offset = 6.7;
};

// ── Stereo calibration data (generated by stereo_calibrate.py) ───
struct CalibrationData {
    cv::Mat M1, D1, M2, D2;        // intrinsics + distortion
    cv::Mat R1, R2, P1, P2, Q;     // rectification + projection
    double focal_length = 0.0;
    double baseline     = 0.0;

    // Camera-to-court 4×4 rigid transform (set by calibrate_court.py).
    Eigen::Matrix4d T_camera_to_court = Eigen::Matrix4d::Identity();

    bool loaded = false;
};

// ── Aggregate config ─────────────────────────────────────────────
struct Config {
    CameraConfig    camera;
    DetectionConfig detection;
    EkfConfig       ekf;
    CalibrationData calibration;
};

// Load the YAML config files from a directory.
Config load_config(const std::string& config_dir);

// Load stereo calibration from an OpenCV FileStorage YAML file.
// Populates config.calibration.
void load_calibration(Config& config, const std::string& calibration_path);

} // namespace baddy
