#pragma once

#include "core/types.hpp"
#include <opencv2/core.hpp>
#include <string>

namespace baddy {

// ── Camera configuration ──────────────────────────────────────────
struct CameraConfig {
    // Acquisition.
    int    fps                      = 100;
    double exposure_us              = 5000;
    bool   exposure_auto            = false;

    // Sensor.
    int    width                    = 1920;
    int    height                   = 1200;
    std::string pixel_format        = "BayerRG8";
    std::string adc_bit_depth       = "Bit10";
    std::string sensor_shutter_mode = "Global";

    // Analog.
    double gain_db                  = 0;
    bool   gain_auto                = false;
    double black_level              = 0.0;
    bool   gamma_enable             = false;

    // White balance.
    bool   white_balance_auto       = false;
    double balance_ratio_red        = 1.28;
    double balance_ratio_blue       = 1.28;

    // Chunk data.
    bool   chunk_mode_active        = true;
    bool   chunk_timestamp          = true;

    // Hardware trigger serials.
    std::string primary_serial;
    std::string secondary_serial;

    // USB transport.
    int    device_link_throughput_limit = 380000000;
};

// ── Detection configuration ───────────────────────────────────────
struct DetectionConfig {
    int hsv_low[3]        = {13, 209, 7};
    int hsv_high[3]       = {15, 226, 255};
    int min_contour_area  = 2;
    int morph_kernel_size = 1;
};

// ── EKF / prediction configuration ───────────────────────────────
struct EkfConfig {
    double alpha    = 0.215;
    double gravity  = 9.81;

    double sigma_p      = 0.05;
    double sigma_v      = 2.0;
    double sigma_cam_x  = 0.02;
    double sigma_cam_y  = 0.02;
    double sigma_cam_z  = 0.05;

    int    max_coast_frames   = 30;
    double target_intercept_y = 0.0;
    double max_predict_time   = 3.0;

    double initial_p_position = 1.0;
    double initial_p_velocity = 100.0;

    // Coordinate remap for the paper dataset.
    std::string x_source = "X";
    std::string y_source = "Z";
    std::string z_source = "Y";
    double x_offset = 3.05;
    double y_offset = 0.0;
    double z_offset = 6.7;
};

// ── Stereo calibration data (generated by stereo_calibrate.py) ───
struct CalibrationData {
    cv::Mat M1, D1, M2, D2;        // intrinsics + distortion
    cv::Mat R1, R2, P1, P2, Q;     // rectification + projection
    double focal_length = 0.0;
    double baseline     = 0.0;

    // Camera-to-court 4×4 rigid transform (set by calibrate_court.py).
    Eigen::Matrix4d T_camera_to_court = Eigen::Matrix4d::Identity();

    bool loaded = false;
};

// ── Aggregate config ─────────────────────────────────────────────
struct Config {
    CameraConfig    camera;
    DetectionConfig detection;
    EkfConfig       ekf;
    CalibrationData calibration;
};

// Load the YAML config files from a directory.
Config load_config(const std::string& config_dir);

// Load stereo calibration from an OpenCV FileStorage YAML file.
// Populates config.calibration.
void load_calibration(Config& config, const std::string& calibration_path);

} // namespace baddy
